<div class="box">
	<img src="<?php echo $this->getSkinUrl('images/advertentieplanet/logo.png'); ?>" style="float:left;margin: 18px 30px 0 10px;"/>
	<p>
		Plaats, beheer, analyseer je producten en verkopen eenvoudig op alle marktplaatsen, shoppingsites en verkoopkanalen. 
		AdvertentiePlanet is een gebruiksvriendelijke multi-channel tool voor webshophouders en marketeers.
	</p>

	<p>Voor documentatie en ondersteuning zie <a href="http://www.advertentieplanet.nl" target="_blank">advertentieplanet.nl</a></p>
    <div style="clear:both;width:1px;height:1px;font-size:1px;overflow:hidden;">&nbsp;</div>
</div>